[package]
name = "qworld-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
qworld-core = { workspace = true }
qworld-fs = { workspace = true }
qworld-bsp = { workspace = true }
qworld-mdl = { workspace = true }
qworld-image = { workspace = true }
qworld-wav = { workspace = true }
qworld-shader = { workspace = true }
qworld-demo = { workspace = true }
qworld-net = { workspace = true }
qworld-render = { workspace = true }
qworld-server = { workspace = true }
glam = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
