[package]
name = "qworld-fs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
qworld-core = { workspace = true }
byteorder = { workspace = true }
thiserror = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
