name: main

on: [push, pull_request, workflow_dispatch]

jobs:
  web:
    name: make-web
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - uses: actions/checkout@v4

      - name: Extract versions
        run: grep 'VER=' engine/Makefile | tee makelibs_versions

      - uses: actions/cache@v4
        id: cache
        with:
          path: engine/libs-*
          key: ${{ runner.os }}-web-${{ hashFiles('makelibs_versions') }}

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: "2.0.12"
          actions-cache-folder: "emsdk-cache-2.0.12"
          cache-key: "emsdk-2.0.12"

      - name: Verify emscripten
        run: emcc -v

      - name: Build dependencies
        working-directory: engine
        run: make FTE_TARGET=web makelibs
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: ammaraskar/gcc-problem-matcher@0.3.0

      - name: Build web
        working-directory: engine
        run: make -j ${{ steps.cpu-cores.outputs.count }} FTE_TARGET=web gl-rel LINK_EZHUD=1 LINK_OPENSSL=1

      - name: Debug release contents
        run: ls -R engine/release

      - name: Format JS artifacts with Prettier
        run: npx prettier@3 --write "engine/release/**/*.js" --log-level debug

      - name: Get version
        id: version
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fteqw-web-${{ steps.version.outputs.short_sha }}
          path: |
            engine/release/fte*
            !engine/release/*.db
          compression-level: 9

  powercam:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: fteqcc-cache
        with:
          path: /usr/local/bin/fteqcc64
          key: ${{ runner.os }}-fteqcc-2024-06-30

      - name: Fetch fteqcc
        run: |
          curl -o fteqcc_linux64.zip https://www.fteqcc.org/dl/fteqcc_linux64.zip
          sudo unzip -d /usr/local/bin fteqcc_linux64.zip fteqcc64
          sudo chmod +x /usr/local/bin/fteqcc64
        if: steps.fteqcc-cache.outputs.cache-hit != 'true'

      - name: Get version
        id: version
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Compile powercam
        working-directory: powercam
        run: make FTEQCC=fteqcc64

      - uses: actions/upload-artifact@v4
        with:
          name: powercam-${{ steps.version.outputs.short_sha }}
          path: |
            powercam/csaddon.*
          compression-level: 9
