name: main

on: [push, pull_request, workflow_dispatch]

jobs:
  make:
    strategy:
      matrix:
        include:
          - name: web
            fte_target: web
            make_targets: "gl-rel"
            os: ubuntu-latest

    name: make-${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - uses: actions/checkout@v4

      - name: Extract versions
        run: grep 'VER=' engine/Makefile | tee makelibs_versions

      - uses: actions/cache@v4
        id: cache
        with:
          path: engine/libs-*
          key: ${{ runner.os }}-${{ matrix.fte_target }}-${{ hashFiles('makelibs_versions') }}

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: "2.0.12"
          actions-cache-folder: "emsdk-cache-2.0.12"
          cache-key: "emsdk-2.0.12"
        if: matrix.fte_target == 'web'

      - name: Verify emscripten
        run: emcc -v
        if: matrix.fte_target == 'web'

      - name: Install dependencies (linux)
        run: sudo apt-get -qq update && sudo apt-get -qq install --no-install-recommends ${{ matrix.packages }}
        if: matrix.packages != '' && matrix.os == 'ubuntu-latest'

      - name: Build dependencies
        working-directory: engine
        run: make FTE_TARGET=${{ matrix.fte_target }} makelibs ${{ matrix.args }}
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: ammaraskar/gcc-problem-matcher@0.3.0

      - name: Build ${{ matrix.name }}
        working-directory: engine
        run: |
          make -j ${{ steps.cpu-cores.outputs.count }} FTE_TARGET=${{ matrix.fte_target }} ${{ matrix.make_targets }} ${{ matrix.args }} LINK_EZHUD=1 LINK_OPENSSL=1

      - name: Debug release contents
        run: ls -R engine/release

      - name: Format JS artifacts with Prettier
        run: npx prettier@3 --write "engine/release/**/*.js" --log-level debug

      - name: Get version
        id: version
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fteqw-${{ matrix.name }}-${{ steps.version.outputs.short_sha }}
          path: |
            engine/release/fte*
            !engine/release/*.db
          compression-level: 9
